name: Deploy Site
on:
  push:
    branches:
      - 'master'
jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.0

      - name: install node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 22.9.0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: install dependencies
        run: pnpm i

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build

  deploy:
    needs: build-website
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
